title: Reverb
subtitle: Creative expression through functional programming.
name: Killian Kelly
description: Creative expression through functional programming.
url: "https://blueishleaf.github.io"
baseurl: "/reverb-lang"
repository: BlueishLeaf/reverb-lang
remote_theme: "mmistakes/minimal-mistakes@4.19.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jemoji
minimal_mistakes_skin: "neon"
author:
  name: "Killian Kelly"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Software Engineer studying at IT Sligo."
  location: "Sligo, Ireland"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/killian-kelly/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BlueishLeaf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BlueishLeaf"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      categories: jekyll update
      author_profile: true
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      sidebar:
        nav: "docs"
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/killian-kelly/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BlueishLeaf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BlueishLeaf"
collections:
  docs:
    output: true
    permalink: /:collection/:path/
include:
  - _pages
